# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    # les deux lignes suivantes ont été ajouté
    http_method_override: false
    handle_all_throwables: true
    # Note that the session will be started ONLY if you read or write from it.
    # session: true // ligne d'origine commentée 
    # insertion des lignes suivantes
    session:
        handler_id : null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
    #remplacement du modèle, vous pouvez modifier le contrôleur qui affiche la page d'erreur
    ##error_controller: App\Controller\ErrorController::show
    #esi: true
    #fragments: true
    php_errors:
        log: true 

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
