twig:
    file_name_pattern: '*.twig'
    # ajout d'un layout bootstrap pour changer le theme sur les formulaires 
    form_themes: ['bootstrap_5_layout.html.twig'] 

when@test:
    twig:
        strict_variables: true
